version: 0.2

phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Building the application 
      - echo Running tests
      - pytest /home/ubuntu/blogprojectdrf/ecom_app/tests
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: no
