version: 0.2

phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Building the application 
      # You can include any additional build commands here
  post_build:
    commands:
      - echo Build completed on `date`
      # You can add any commands here that you want to run after the build

artifacts:
  files:
    - '**/*'
  base-directory: /home/ubuntu/blogprojectdrf
  discard-paths: no