name: Run Pytest

on:
  repository_dispatch:
    types: [run-pytest]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pytest and WebDriver Manager
      run: |
        pip install pytest selenium webdriver-manager
    
    - name: List files in repository
      run: |
        ls -R

    - name: Run tests
      run: |
        pytest tests/login_test.py
      continue-on-error: true

    - name: Report results
      if: failure()
      run: |
        echo "Tests failed" 
      if: success()
      run: |
        echo "Tests passed"
