name: Run Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: install pytest
      run: |
        pip install pytest

    - name: Install WebDriver Manager
      run: |
        pip install webdriver-manager
    
    - name: List files in repository
      run: |
        ls -R

    - name: Run tests
      run: |
        pytest tests/test_login.py

